env:
  browser: true
  es2021: true
  jest: true
extends: airbnb-base
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {
  no-console: off,
  import/extensions: off,
  no-underscore-dangle: ["error", { "allow": ["__filename", "__dirname"] }],
  no-param-reassign: off
}